spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/echo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    # 主机号
    host: localhost
    #端口号
    port: 6379
    #超时时间
    timeout: 1800000
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 20
        #最大阻塞等待时间(-1表示没有限制)
        max-wait: -1
        #最大空闲连接
        max-idle: 5
        #最小空闲连接
        min-idle: 0

